import { CategoryPortfolioEnum, PortfolioType } from './types';

export const PORTFOLIO_LIST: PortfolioType[] = [
  {
    id: 'swizaesar-portfolio',
    urlId: 1,
    key: 'swizaesar_portfolio',
    category: CategoryPortfolioEnum.WEB_APP,
    techStack: [
      'Next.js',
      'React.js',
      'TypeScript',
      'Emotion.js',
      'Lucide React',
    ],
    websiteUrl: 'https://swizaesar.com',
  },
  {
    id: 'fithub-website',
    urlId: 2,
    key: 'fithub_website',
    category: CategoryPortfolioEnum.WEB_APP,
    techStack: [
      'Next.js',
      'React.js',
      'TypeScript',
      'Emotion.js',
      'Redux',
      'Axios',
    ],
    websiteUrl: 'https://fithub.id',
  },
  {
    id: 'fithub-dashboard',
    urlId: 3,
    key: 'fithub_dashboard',
    category: CategoryPortfolioEnum.DASHBOARD,
    techStack: [
      'React.js',
      'Vite.js',
      'TypeScript',
      'Redux',
      'Ant Design',
      'Styled Components',
      'Axios',
    ],
  },
  {
    id: 'tataskola-dashboard',
    urlId: 4,
    key: 'tataskola_dashboard',
    category: CategoryPortfolioEnum.DASHBOARD,
    techStack: ['React.js', 'Material UI', 'Redux', 'Axios', 'Firebase'],
  },
  {
    id: 'lakugan-platform',
    urlId: 5,
    key: 'lakugan_platform',
    category: CategoryPortfolioEnum.WEB_APP,
    techStack: [
      'React.js',
      'Styled Components',
      'Context API',
      'Ant Design',
      'Axios',
    ],
  },
  {
    id: 'nusamed-website',
    urlId: 6,
    key: 'nusamed_website',
    category: CategoryPortfolioEnum.LANDING_PAGE,
    techStack: ['React.js', 'Styled Components'],
    websiteUrl: 'https://nusamed.com',
  },
];
